### PR TITLE
Links in flash body should be white

### PR DESCRIPTION
**Pull request by jrubenoff**
Just fixing stuff I notice as I'm creating dummy content for the video...

Links in the flash body are currently showing up as blue, not white.

Fix:

screen shot 2015-12-15 at 2 39 18 pm

### CODE REVIEW

**Comment by ajb** [comment]
Looks good, but... where are we using this pattern? I thought we switched to using `.flash_links` for any links.

**Comment by jrubenoff** [comment]
Can't seem to reproduce or find the source, but when I tried to create a Screendoor project without a plan, I got an error message that resembled this:

screen shot 2015-12-15 at 3 30 11 pm

**Comment by ajb** [comment]
Cool. That's in `auth`. 

Should we fix it to use the `.flash_links`, or should we merge this PR? I'd prefer to keep our styles non-duplicative unless there's a reason to... up to you.

**Comment by jrubenoff** [comment]
We can use `.flash_links`, but I'd like to merge this PR to keep our styles bulletproof in case this happens again.

**Pull request merged**
