### PR TITLE
Add CSS animations test and conditional loading to Modernizr

### PR DESCRIPTION
**Pull request by jrubenoff**
Required for dobtco/screendoor-v2#2368

### CODE REVIEW

**Comment by ajb** [comment]
Looks like you added a lot more than just `cssanimations`:

img

Can you tell me why you need Modernizr.load?

**Comment by jrubenoff** [comment]
I did add the shiv as well, you're right. Not sure why we didn't have that before.

Everything else comes with Modernizr.load.

> Can you tell me why you need Modernizr.load?

See dobtco/screendoor-v2#2368

**Comment by ajb** [comment]
We're loading the shiv separately.  AFAICT `Modernizr.load` can be replaced with and `if` statement and `$.getScript`. Let's chat about this and screendoor-v2#2368 later today or tomorrow.

**Comment by jrubenoff** [comment]
Just removed the shiv.

Modernizr.load also contains [`nope` and `complete` options](http://modernizr.com/docs/#load), which I will want to use going forward.

**Pull request closed without merging**
