### PR TITLE
Switch from capybara-webkit to poltergeist for specs.

### PR DESCRIPTION
**Pull request by vlymar**
capybara-webkit depends on QT, which is a nightmare.

See https://github.com/dobtco/our-boxen/issues/21#issuecomment-282429635 for
more info.

### CODE REVIEW

**Comment by vlymar** [comment]
trying to understand if https://percy.io/dobtco/dvl-core/builds/278910?snapshot=8679699 is actually a problem or not. As far as I can tell it just seems like poltergeist renders the dropdown a bit less wide than capybara webkit, which doesn't seem like a real problem.

**Comment by jrubenoff** [comment]
…Yeah, I feel like that’s OK

**Comment by vlymar** [comment]
@drusepth, just wanted to explain what was going on here.

We used to use capybara-webkit as our capybara driver (its basically a headless browser). capybara-webkit depends on QT, which is sorta a nightmarish dependency that has gotten more and more difficult to support, particularly on macOS. Adam had already started using poltergeist (backed by phantomJS) in screendoor , so I decided to just move everything else to poltergeist as well, which allows us to remove the QT dependency from our dev environment.

This was a repo I missed, so when Josh tried to bundle here recently it failed.

You can ignore the percy failure, it looks like just a minor difference between how the dropdown is rendered between QT and phantom. Also disregard all my intermediate commits.

`js_errors: false` matches the previous behavior capybara-webkit

**Comment by vlymar** [comment]
just looking for a quick sanity check here, dont think this is worth deep thought

**Comment by vlymar** [comment]
This was a minor enough change that i didn't think it needed review.

**Pull request merged**
