### PR TITLE
Add "dvl-icons" iconset

### PR DESCRIPTION
**Pull request by ajb**
cf #107

### CODE REVIEW

**Comment by ajb** [comment]
@jrubenoff, just let me know if you have any questions about the build process or anything else!

**Comment by jrubenoff** [comment]
When I run Grunt in `dvl-icons` and update the gem in this branch, the font and the list of icon names are reflected, but the stylesheet isn't.

To keep working on this, I've copied the updated stylesheet from `dvl-icons` into this branch as a temporary measure.

**Comment by ajb** [comment]
Did you restart the `script/server` process?

**Comment by jrubenoff** [comment]
[The final nail in the coffin...](https://github.com/blog/2112-delivering-octicons-with-svg)

Will convert these to SVG at some point in the next few weeks. Using a consistent stroke width across dimensions will go a long way towards making this merge-able.

**Comment by ajb** [comment]
This is still a *ton* of work. I'd prefer to hold on this for now...

On Tue, Feb 23, 2016 at 3:17 PM, Josh Rubenoff <notifications@github.com>
wrote:

> The final nail in the coffin...
> <https://github.com/blog/2112-delivering-octicons-with-svg>
>
> Will convert these to SVG at some point in the next few weeks. Using a
> consistent stroke width across dimensions will go a long way towards making
> this merge-able.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/pull/199#issuecomment-187885377>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Moving discussion to https://github.com/dobtco/dobt/issues/1503, and closing this since we'll be using another branch anyway.

**Pull request closed without merging**
