### PR TITLE
Improved page header styles

### PR DESCRIPTION
**Pull request by jrubenoff**
Also easier for those with color blindness to understand which link is active.

screen shot 2015-09-08 at 10 18 46 am

### CODE REVIEW

**Comment by ajb** [comment]
Does this address #136 and #144? If not, can it?

**Comment by jrubenoff** [comment]
Thanks for pointing those out! Fixed #136 and commented on #144. Still need to modify Screendoor accordingly, though.

**Comment by ajb** [comment]
Awesome, looks great. Just pulled it down and have one comment, which is that the `.active` text is a bit light for my liking. What do you think of using `$bodyFontColor` instead of `$primaryColor`? Or maybe making it bold?

img

**Comment by jrubenoff** [comment]
I like how it looks in Screendoor, so I just added a darker primary color to `dvl-core` instead.

**Comment by ajb** [comment]
I don't think we should be using `$primaryColor` for typography -- think about how it would look on Autodrip where the brand color is #513847. (purple)

I'm gonna make that change, but I'll wait for your :+1: before merging.

**Comment by jrubenoff** [comment]
I want the selected state to be a darker shade of blue, so I just added it as a variable: `$linkSelectedColor`. Does that work?

**Comment by ajb** [comment]
:ok_hand:

**Pull request merged**
