### PR TITLE
add full selectize styles

### PR DESCRIPTION
**Pull request by ajb**
cf https://github.com/dobtco/dvl-core/issues/184

### CODE REVIEW

**Comment by ajb** [comment]
@jrubenoff: you can use http://dvlcore.dev/regression/selectize to test this out. You'll also get to fix / re-apply the styles that I created in https://github.com/dobtco/dvl-core/pull/164, since I just clobbered everything by using selectize's `.less` source files. (Converted to `.scss`, of course.)

**Comment by jrubenoff** [comment]
So I took a first crack at the styles. They're not finished, but, two questions:

1. Are we replacing our `.styled_selects` with selectize?
2. Are we planning to use multiple selects for anything outside of respondent view?

**Comment by ajb** [comment]
> Are we replacing our .styled_selects with selectize?

No

> Are we planning to use multiple selects for anything outside of respondent view?

DOBT Admin: 

img

**Comment by jrubenoff** [comment]
Well, this took a while, but it's now properly styled.

**Comment by ajb** [comment]
Awesome, thanks! It looks great.

Here are a couple small bugs I found:

Adding multiple lines of items should vertically expand the "input" area:

screen shot 2016-01-11 at 11 26 57 am

"Single dropdown" height should stay the same when opening/closing: http://take.ms/Vh51s

Also, the caret should probably not invert, to stay consistent with our other dropdown behavior.

**Comment by jrubenoff** [comment]
Fixed the first two issues.

I think the caret should stay inverted, to indicate that the behavior isn't consistent with our other dropdowns (like `.dropdown_menu`).

**Comment by ajb** [comment]
First issue looks fixed -- I'm still seeing the second one when I select an item from the Selectize dropdown.

**Comment by jrubenoff** [comment]
Ah. Just fixed.

**Comment by ajb** [comment]
Awesome, thanks!

**Pull request merged**
