### PR TITLE
Fix for #30

### PR DESCRIPTION
**Pull request by jrubenoff**
Change `.dropdown_toggle_button` to `display: block;`

### CODE REVIEW

**Comment by ajb** [comment]
Err, isn't this side-effect kinda drastic?

img

I've fixed this in a commit, not sure if will have unintended side-effects or not...

**Comment by ajb** [comment]
Also, a friendly reminder about commit/PR messages :)

**Comment by ajb** [comment]
Are these CSS tweaks for formrenderer, or Screendoor? 

1. You'll notice that for better or worse, formrenderer uses `px` values in its CSS. I'd like to either stick with this, or rework the entire file to use `rem` or `em` units.

2. There's a layout error here, which is why I was using absolute positioning:

img

**Comment by ajb** [comment]
Can you follow-up?

**Comment by jrubenoff** [comment]
I think dobtco/formrenderer-base#24 should take care of this.

**Pull request merged**
