### PR TITLE
add regression testing specs

### PR DESCRIPTION
**Pull request by ajb**
cf #113.

- this test will fail if there's significant visual difference between the old and new behavior of a test
- to create a new regression spec, we would create an isolated view (a la  `/spec/dummy/app/views/home/regression/dropdown.rb`), and add a test to `spec/regression_spec.rb`)

See https://github.com/ronen/rspec-page-regression for more.

I think this is handy to have, especially for interactive bits. I would consider adding regression specs for:

- Dropdowns (all variations)
- Selects
- Dropdown selects
- Modals
- Checkbox/radio (since styling these is so tricky)

### CODE REVIEW

**Comment by ajb** [comment]
@jrubenoff: curious to hear your thoughts on this.

**Comment by jrubenoff** [comment]
Seems :+1: to try out, at least.

**Comment by jrubenoff** [comment]
Just realized Github doesn't allow comments on images, so, one qualifier: assuming `expected.png` is automatically generated, it doesn't appear to be loading Typekit fonts.

Something to keep in mind if tests are generating screenshots that look "broken", even when the style guide is fine.

**Comment by ajb** [comment]
Yeah, so the dummy app runs on the `example.com` host, which we need to whitelist for Typekit.

Also, I've gotta figure out why the specs are failing before this can get merged.

**Pull request closed without merging**
