### PR TITLE
bring rich dropdown elements into focus when opening

### PR DESCRIPTION
**Pull request by ajb**
cf #248

@jrubenoff, I could use your opinion here. (Once you're back!)

Here's a screencast: http://take.ms/hpwPH

### CODE REVIEW

**Comment by jrubenoff** [comment]
What if we just positioned the dropdown menu above the button in these instances, instead of below it?

screen shot 2016-07-11 at 2 01 34 pm
 
This would more closely replicate the behavior of existing `select`s, and remove the abrupt / awkward shift in page position that this approach requires.

**Comment by ajb** [comment]
That would be about 100x more complicated to implement. If this is an improvement, we should merge it -- if not, I don't really have any other options. (I worked at this for a while...)

**Comment by jrubenoff** [comment]
Well, just looked at the original issue, which clarifies things a bit!

So...

- Like #248 depicts, is there any way we can scroll the selected item as close to the top of the list as possible? As it stands, the scrolling behavior seems a little arbitrary.

- Re: the bottom-of-viewport stuff, what I suggested above is how iOS does it. You can see another manifestation of the same problem in #129. Right now, it looks like it's a "won't fix" Bootstrap issue (see [this](https://github.com/twbs/bootstrap/issues/3637), and [fat's comment that this might be a perf problem.](https://github.com/twbs/bootstrap/issues/7399#issuecomment-18439919))

   We should keep thinking about ways to solve this in the future, beyond this issue... it's still pretty annoying for responsive design, and for smaller screens.

- In the meantime, would it be too expensive to (rapidly) smooth-scroll the window if the dropdown's at the bottom of the viewport? As mentioned, right now it feels a little abrupt.

**Comment by ajb** [comment]
Please look at the implementation. There is no flexibility on how it behaves.

**Comment by jrubenoff** [comment]
Couldn't you..

- set the `$.scrolltop` of `.dropdown` to `li.active a`
-  animate the scroll position
- _then_ focus it?

**Comment by ajb** [comment]
I tried that, but I was having trouble figuring out how to get the correct offset of `li.active a`. Also, there's no guarantee where it will be positioned once it's `.focus()`ed.

If you'd like to pair on this, we can try, but I spent a while trying to make this work.

**Comment by ajb** [comment]
In person: we went over my comment above ^^.

**Pull request merged**
