### PR TITLE
Page subheader bug fix

### PR DESCRIPTION
**Pull request by aviv**
closes https://github.com/dobtco/screendoor-v2/issues/2241
merge with https://github.com/dobtco/screendoor-v2/pull/2287

### CODE REVIEW

**Comment by jrubenoff** [comment]
This changes our existing styles for page subheaders:

screen shot 2015-07-27 at 2 01 24 pm

We need a new pattern for the lock icon.

**Comment by ajb** [comment]
Alternatively, we could just remove the `icon_private` component entirely, unless we think it's really necessary to have? I mean, it's kinda redundant, there's a lot of things in Screendoor that are "visible only to collaborators with appropriate permissions", yet don't have an `icon_private` next to them.

**Comment by aviv** [comment]
Yep, I actually agree. Doesn't seem necessary, at least here. Not sure if there's anywhere else where it's more relevant/necessary.

**Comment by ajb** [comment]
You could `grep` for it?

**Comment by jrubenoff** [comment]
:+1:

**Pull request closed without merging**
