### PR TITLE
consistent line height for inputs/textareas/selects

### PR DESCRIPTION
**Pull request by ajb**
Closes https://github.com/dobtco/dvl-core/pull/34

### CODE REVIEW

**Comment by ajb** [comment]
Went with the `height` for inputs and `line-height` for textareas solution. Really excited to get a consistent height for our inputs, textareas, and selects... it's been bugging me for a while.

Here's the results of Browserstack screenshots: http://www.browserstack.com/screenshots/33e8007735d50cf8a8b49679b2013ecdf8905ba3

**Comment by jrubenoff** [comment]
Alllrighty

**Comment by ajb** [comment]
Can you be more explicit? Is this good to merge?

**Comment by jrubenoff** [comment]
Sorry, yes, go for it.

**Comment by ajb** [comment]
Np, thanks for reviewing!

**Pull request merged**
