### PR TITLE
New flash styles

### PR DESCRIPTION
**Pull request by ajb**
Rebase of #83.

I refactored some of the code and tried to fix the bugs that I found with transitions, etc.

@jrubenoff: assuming the output looks good, do you want to take a quick look to see if there's any refactoring you can do of the CSS? It looks a little messy to my eyes, which would make sense given the many iterations of flashes that we went through.

### CODE REVIEW

**Comment by ajb** [comment]
I just noticed that our neutral flash is now gray instead of blue. I think blue might look better -- gray is lacking in contrast to other elements on the page.

Here's an example:

img

**Comment by ajb** [comment]
Additional question: do we need an option to customize the icon that's displayed?

img

**Comment by jrubenoff** [comment]
Fixed some styles:

screen shot 2015-10-28 at 2 43 38 pm

Where did the persistent flashes go? We need them for shortcuts.

Shortcut flashes will just have the `.flash_shortcut` class in Screendoor.

**Comment by ajb** [comment]
It looks like persistent flashes are "any flashes that have links". Is this
an incorrect assumption?

On Wed, Oct 28, 2015 at 2:44 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Fixed some styles:
>
> [image: screen shot 2015-10-28 at 2 43 38 pm]
> <https://cloud.githubusercontent.com/assets/1328849/10803993/538c3ebe-7d82-11e5-9387-2545a2900eda.png>
>
> Where did the persistent flashes go? We need them for shortcuts.
>
> Shortcut flashes will just have the .flash_shortcut class in Screendoor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/pull/196#issuecomment-152004296>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
Nope, that sounds accurate

**Comment by ajb** [comment]
OK, perfect. I left the persistent flashes in, but instead of passing a
separate "persistent" flag, the JS just checks to see if there are any
links present.

On Wed, Oct 28, 2015 at 2:55 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Nope, that sounds accurate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/dvl-core/pull/196#issuecomment-152006509>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
:boom:

Really happy to be shipping this!

**Pull request merged**
