### PR TITLE
Add delete confirmations to style guide [BREAKING]

### PR DESCRIPTION
**Pull request by ajb**
cf https://github.com/dobtco/dvl-core/pull/101#issuecomment-109139028

I added three kinds of delete confirmations to the "Components" page.

(Also, this PR makes breaking changes to the way our javascript is structured.)

----

### New JS

- dvl/components/modal_helper (translate)
- dvl/components/confirmations (translate)
- dvl/components/rails_allow_action

### Namespace changes

- `DvlFlash` -> `Dvl.Flash`
- `DvlFlashHide` -> `Dvl.FlashHide`

### CODE REVIEW

**Comment by jrubenoff** [comment]
I had a lot of trouble changing the show / hide animations for the popovers here, which seems weird... don't we use Bootstrap popovers in respondent view? So I just disabled them entirely... the slow fade in and out is inconsistent with our other overlays. Would be great if I could properly change them later.

Anyway, this is OK with me to merge.

**Comment by ajb** [comment]
Let's see if we can figure it out in our checkin.

**Comment by ajb** [comment]
- I'm gonna take a shot at fixing the transform animation, and if it's not possible, we'll merge as-is
- After merging, open PR to implement in Screendoor

**Comment by ajb** [comment]
Gonna merge without animations.

Always happy to accept a PR for animations, but I think anything with a `scale` transform is going to break the positioning.

**Pull request merged**
