### PR TITLE
Force height for .input_group_small

### PR DESCRIPTION
**Pull request by jrubenoff**
Should fix dobtco/screendoor-v2#2942...

### CODE REVIEW

**Comment by ajb** [comment]
looks like this doesn't compile?

**Comment by jrubenoff** [comment]
Apologies, just fixed a typo.

**Comment by ajb** [comment]
This does not fix the issue:

screen shot 2016-01-06 at 10 05 40 am

**Comment by jrubenoff** [comment]
Seems that when I fixed this initially in the Web Inspector, I overlooked that I added `display: table-row` to all `.input_groups`. Will test this change throughout Screendoor before asking to merge.

**Pull request closed without merging**
