### PR TITLE
Add microcopy styles, add to style guide

### PR DESCRIPTION
**Pull request by jrubenoff**
Required for dobtco/screendoor-v2#3272

### CODE REVIEW

**Comment by ajb** [comment]
Looks good. I'm gonna move the preview to the `/forms` page, since that's where the scss lives.

**Comment by ajb** [comment]
Actually, there was already a microcopy component on the `/forms` page, so I fixed that.

Can you help clarify for me... what's the intended markup for microcopy? Is it:

```
div(class: 'microcopy') {
  p 'foo'
}
```

or

```
div(class: 'microcopy') {
  p 'foo'
  a 'bar', class: 'button small'
}
```

or

```
div(class: 'microcopy') {
  span 'foo'
}
```

The CSS is a bit confusing, or is it just crufty?

**Comment by jrubenoff** [comment]
Removed some unused styles. You can have no markup in there (like in the
dashboard), or a p tag with an optional button at the bottom.

**Comment by ajb** [comment]
:+1: Thanks!

**Pull request merged**
