### PR TITLE
Consistent user avatar corner radius

### PR DESCRIPTION
**Pull request by jrubenoff**

### CODE REVIEW

**Comment by ajb** [comment]
It doesn't actually look like this mixin is being used anywhere. Is that an oversight or did I miss something?

**Comment by jrubenoff** [comment]
See the Screendoor navbar.

**Comment by ajb** [comment]
Right, but it's not actually using this mixin: https://github.com/dobtco/dvl-core/blob/5edaf5c9018cc6504b569e362b833460b0442869/vendor/assets/stylesheets/dvl/components/navbar.scss#L89

**Comment by jrubenoff** [comment]
You're right. Sorry for the confusion. Let's just delete it, then...

**Pull request merged**
