### PR TITLE
fix horizontal legends

### PR DESCRIPTION
**Pull request by ajb**
@jrubenoff: can you confirm that this is the correct fix?

### CODE REVIEW

**Comment by ajb** [comment]
Might need some browser fixes, too. Here's IE9:

img

**Comment by jrubenoff** [comment]
Can you clarify why this fix is needed?

I changed the way we're fixing this... we don't need to add a float here.

**Comment by ajb** [comment]
Here's why the fix is needed:

img

This is with your latest commits. I can't figure out how to fix...

**Comment by jrubenoff** [comment]
I think IE9 sets`text-align` by default for `legend`s... just fixed.

**Comment by ajb** [comment]
Still looks like this in latest Safari on OS X:

img

**Comment by ajb** [comment]
Added the float back, which fixes Safari.

Tested on Chrome, Safari, FF on my mac.

Tested on a whole bunch of devices on Browserstack using their screenshots feature: https://www.browserstack.com/screenshots/281c7cf17cf2c4fdd68e826df03df66f94bf81f7

With this amount of testing, I'm comfortable merging.

**Pull request merged**
